//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAdmin.ServicioCatalagos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstatusCLS", Namespace="http://schemas.datacontract.org/2004/07/CatalagosComercializadoraWCF.DTO")]
    [System.SerializableAttribute()]
    public partial class EstatusCLS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstatus {
            get {
                return this.IdEstatusField;
            }
            set {
                if ((this.IdEstatusField.Equals(value) != true)) {
                    this.IdEstatusField = value;
                    this.RaisePropertyChanged("IdEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstatus {
            get {
                return this.NombreEstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstatusField, value) != true)) {
                    this.NombreEstatusField = value;
                    this.RaisePropertyChanged("NombreEstatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolCLS", Namespace="http://schemas.datacontract.org/2004/07/CatalagosComercializadoraWCF.DTO")]
    [System.SerializableAttribute()]
    public partial class RolCLS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRol {
            get {
                return this.NombreRolField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreRolField, value) != true)) {
                    this.NombreRolField = value;
                    this.RaisePropertyChanged("NombreRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int IdEstatus {
            get {
                return this.IdEstatusField;
            }
            set {
                if ((this.IdEstatusField.Equals(value) != true)) {
                    this.IdEstatusField = value;
                    this.RaisePropertyChanged("IdEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string NombreEstatus {
            get {
                return this.NombreEstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstatusField, value) != true)) {
                    this.NombreEstatusField = value;
                    this.RaisePropertyChanged("NombreEstatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCatalagos.ICatalagos")]
    public interface ICatalagos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/ListaEstatus", ReplyAction="http://tempuri.org/ICatalagos/ListaEstatusResponse")]
        PortalAdmin.ServicioCatalagos.EstatusCLS[] ListaEstatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/ListaEstatus", ReplyAction="http://tempuri.org/ICatalagos/ListaEstatusResponse")]
        System.Threading.Tasks.Task<PortalAdmin.ServicioCatalagos.EstatusCLS[]> ListaEstatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/ListaRoles", ReplyAction="http://tempuri.org/ICatalagos/ListaRolesResponse")]
        PortalAdmin.ServicioCatalagos.RolCLS[] ListaRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/ListaRoles", ReplyAction="http://tempuri.org/ICatalagos/ListaRolesResponse")]
        System.Threading.Tasks.Task<PortalAdmin.ServicioCatalagos.RolCLS[]> ListaRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/recuperarRol", ReplyAction="http://tempuri.org/ICatalagos/recuperarRolResponse")]
        PortalAdmin.ServicioCatalagos.RolCLS recuperarRol(int IdRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/recuperarRol", ReplyAction="http://tempuri.org/ICatalagos/recuperarRolResponse")]
        System.Threading.Tasks.Task<PortalAdmin.ServicioCatalagos.RolCLS> recuperarRolAsync(int IdRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/RegistrarYActualizarRol", ReplyAction="http://tempuri.org/ICatalagos/RegistrarYActualizarRolResponse")]
        int RegistrarYActualizarRol(PortalAdmin.ServicioCatalagos.RolCLS obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/RegistrarYActualizarRol", ReplyAction="http://tempuri.org/ICatalagos/RegistrarYActualizarRolResponse")]
        System.Threading.Tasks.Task<int> RegistrarYActualizarRolAsync(PortalAdmin.ServicioCatalagos.RolCLS obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/EliminarRol", ReplyAction="http://tempuri.org/ICatalagos/EliminarRolResponse")]
        int EliminarRol(int IdRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalagos/EliminarRol", ReplyAction="http://tempuri.org/ICatalagos/EliminarRolResponse")]
        System.Threading.Tasks.Task<int> EliminarRolAsync(int IdRol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalagosChannel : PortalAdmin.ServicioCatalagos.ICatalagos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalagosClient : System.ServiceModel.ClientBase<PortalAdmin.ServicioCatalagos.ICatalagos>, PortalAdmin.ServicioCatalagos.ICatalagos {
        
        public CatalagosClient() {
        }
        
        public CatalagosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalagosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalagosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalagosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PortalAdmin.ServicioCatalagos.EstatusCLS[] ListaEstatus() {
            return base.Channel.ListaEstatus();
        }
        
        public System.Threading.Tasks.Task<PortalAdmin.ServicioCatalagos.EstatusCLS[]> ListaEstatusAsync() {
            return base.Channel.ListaEstatusAsync();
        }
        
        public PortalAdmin.ServicioCatalagos.RolCLS[] ListaRoles() {
            return base.Channel.ListaRoles();
        }
        
        public System.Threading.Tasks.Task<PortalAdmin.ServicioCatalagos.RolCLS[]> ListaRolesAsync() {
            return base.Channel.ListaRolesAsync();
        }
        
        public PortalAdmin.ServicioCatalagos.RolCLS recuperarRol(int IdRol) {
            return base.Channel.recuperarRol(IdRol);
        }
        
        public System.Threading.Tasks.Task<PortalAdmin.ServicioCatalagos.RolCLS> recuperarRolAsync(int IdRol) {
            return base.Channel.recuperarRolAsync(IdRol);
        }
        
        public int RegistrarYActualizarRol(PortalAdmin.ServicioCatalagos.RolCLS obj) {
            return base.Channel.RegistrarYActualizarRol(obj);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarYActualizarRolAsync(PortalAdmin.ServicioCatalagos.RolCLS obj) {
            return base.Channel.RegistrarYActualizarRolAsync(obj);
        }
        
        public int EliminarRol(int IdRol) {
            return base.Channel.EliminarRol(IdRol);
        }
        
        public System.Threading.Tasks.Task<int> EliminarRolAsync(int IdRol) {
            return base.Channel.EliminarRolAsync(IdRol);
        }
    }
}
