// <auto-generated />
namespace DatabaseCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class provedor_productos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(provedor_productos));
        
        string IMigrationMetadata.Id
        {
            get { return "202202240414099_provedor_productos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
